/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package iapuzzlev1;


public class PuzzleV1 extends javax.swing.JFrame {
       public String[][] matriz_juego = new String[3][3];
    /**
     * Creates new form PuzzleV1
     */
    public PuzzleV1() {
        initComponents();
        btn_Black.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Grupo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btn_Black = new javax.swing.JButton();
        btn_A = new javax.swing.JButton();
        btn_B = new javax.swing.JButton();
        btn_C = new javax.swing.JButton();
        btn_D = new javax.swing.JButton();
        btn_E = new javax.swing.JButton();
        btn_F = new javax.swing.JButton();
        btn_G = new javax.swing.JButton();
        btn_H = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Next_Step = new javax.swing.JButton();
        textArea1 = new java.awt.TextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(3, 3));

        btn_Black.setText("*");
        btn_Black.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BlackActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Black);

        btn_A.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgA.jpg"))); // NOI18N
        btn_A.setText("A");
        btn_A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AActionPerformed(evt);
            }
        });
        jPanel1.add(btn_A);

        btn_B.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgB.jpg"))); // NOI18N
        btn_B.setText("B");
        btn_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BActionPerformed(evt);
            }
        });
        jPanel1.add(btn_B);

        btn_C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgC.jpg"))); // NOI18N
        btn_C.setText("C");
        btn_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CActionPerformed(evt);
            }
        });
        jPanel1.add(btn_C);

        btn_D.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgD.jpg"))); // NOI18N
        btn_D.setText("D");
        btn_D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DActionPerformed(evt);
            }
        });
        jPanel1.add(btn_D);

        btn_E.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgE.jpg"))); // NOI18N
        btn_E.setText("E");
        btn_E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EActionPerformed(evt);
            }
        });
        jPanel1.add(btn_E);

        btn_F.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgF.jpg"))); // NOI18N
        btn_F.setText("F");
        btn_F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FActionPerformed(evt);
            }
        });
        jPanel1.add(btn_F);

        btn_G.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgG.jpg"))); // NOI18N
        btn_G.setText("G");
        btn_G.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GActionPerformed(evt);
            }
        });
        jPanel1.add(btn_G);

        btn_H.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgH.jpg"))); // NOI18N
        btn_H.setText("H");
        btn_H.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HActionPerformed(evt);
            }
        });
        jPanel1.add(btn_H);

        jButton1.setText("Automático");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Next_Step.setText("Siguiente Movimiento");
        Next_Step.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Next_StepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Next_Step)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(textArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 35, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(43, 43, 43)
                                .addComponent(Next_Step))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(textArea1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_BlackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BlackActionPerformed
       
        javax.swing.JButton btn_aux = new javax.swing.JButton();
         
        if(btn_A.isVisible()==false){
             btn_aux.setText(btn_Black.getText());
             btn_aux.setIcon(btn_Black.getIcon());
             
             btn_Black.setText(btn_A.getText()); 
             btn_Black.setIcon(btn_A.getIcon()); 
             
             btn_A.setText(btn_aux.getText());
             btn_A.setIcon(btn_aux.getIcon());
             
             btn_Black.setVisible(false);
             btn_A.setVisible(true);
             
        }
         else{
            if(btn_C.isVisible()==false){
                btn_aux.setText(btn_Black.getText());
                btn_aux.setIcon(btn_Black.getIcon());
                
                btn_Black.setText(btn_C.getText());
                btn_Black.setIcon(btn_C.getIcon()); 
                
                btn_C.setText(btn_aux.getText());
                btn_C.setIcon(btn_aux.getIcon());
                btn_Black.setVisible(false);
                btn_C.setVisible(true);
            }
            else{
                    System.out.println("No se puede mover");
                }
        } 
    }//GEN-LAST:event_btn_BlackActionPerformed

    private void btn_AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AActionPerformed
 
        javax.swing.JButton btn_aux = new javax.swing.JButton();
        
        if(btn_Black.isVisible()==false){
            btn_aux.setText(btn_A.getText());
            btn_aux.setIcon(btn_A.getIcon());
            
            btn_A.setText(btn_Black.getText());
             btn_A.setIcon(btn_Black.getIcon());
             
            btn_Black.setText(btn_aux.getText());
            btn_Black.setIcon(btn_aux.getIcon());
            btn_A.setVisible(false);
            btn_Black.setVisible(true);
        }
        else{
            if(btn_B.isVisible()==false){
                btn_aux.setText(btn_A.getText());
                btn_aux.setIcon(btn_A.getIcon());
                
                btn_A.setText(btn_B.getText());
                btn_A.setIcon(btn_B.getIcon());
                
                btn_B.setText(btn_aux.getText());
                btn_B.setIcon(btn_aux.getIcon());
                btn_A.setVisible(false);
                btn_B.setVisible(true);
            }
            else{
                if(btn_D.isVisible()==false){
                    btn_aux.setText(btn_A.getText()); 
                    btn_aux.setIcon(btn_A.getIcon());
                    
                    btn_A.setText(btn_D.getText());
                    btn_A.setIcon(btn_D.getIcon());
                    
                    btn_D.setText(btn_aux.getText());
                    btn_D.setIcon(btn_aux.getIcon());
                    btn_A.setVisible(false);
                    btn_D.setVisible(true);
                }
                else{
                    System.out.println("No se puede mover");
                }
            }
        }

    }//GEN-LAST:event_btn_AActionPerformed
        
    private void btn_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CActionPerformed
       
         javax.swing.JButton btn_aux = new javax.swing.JButton();
        
        if(btn_Black.isVisible()==false){
            btn_aux.setText(btn_C.getText());
            btn_aux.setIcon(btn_C.getIcon());
            
            btn_C.setText(btn_Black.getText());
             btn_C.setIcon(btn_Black.getIcon());
             
            btn_Black.setText(btn_aux.getText());
            btn_Black.setIcon(btn_aux.getIcon());
            btn_C.setVisible(false);
            btn_Black.setVisible(true);
        }
        else{
            if(btn_D.isVisible()==false){
                btn_aux.setText(btn_C.getText());
                btn_aux.setIcon(btn_C.getIcon());
                
                btn_C.setText(btn_D.getText());
                btn_C.setIcon(btn_D.getIcon());
                
                btn_D.setText(btn_aux.getText());
                btn_D.setIcon(btn_aux.getIcon());
                btn_C.setVisible(false);
                btn_D.setVisible(true);
            }
            else{
                if(btn_F.isVisible()==false){
                    btn_aux.setText(btn_C.getText());
                    btn_aux.setIcon(btn_C.getIcon());
                    
                    btn_C.setText(btn_F.getText());
                    btn_C.setIcon(btn_F.getIcon());
                    
                    btn_F.setText(btn_aux.getText());
                    btn_F.setIcon(btn_aux.getIcon());
                    btn_C.setVisible(false);
                    btn_F.setVisible(true);
                }
                else{
                    System.out.println("No se puede mover");
                }
            }
        }

    }//GEN-LAST:event_btn_CActionPerformed

    private void btn_DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DActionPerformed
        
       javax.swing.JButton btn_aux = new javax.swing.JButton();
        
        if(btn_A.isVisible()==false){
            btn_aux.setText(btn_D.getText());
            btn_aux.setIcon(btn_D.getIcon());
            
            btn_D.setText(btn_A.getText());
            btn_D.setIcon(btn_A.getIcon());
            
            btn_A.setText(btn_aux.getText());
            btn_A.setIcon(btn_aux.getIcon());
            btn_D.setVisible(false);
            btn_A.setVisible(true);
        }
        else{
            if(btn_E.isVisible()==false){
                btn_aux.setText(btn_D.getText());
                btn_aux.setIcon(btn_D.getIcon());
                
                btn_D.setText(btn_E.getText());
                btn_D.setIcon(btn_E.getIcon());
                
                btn_E.setText(btn_aux.getText());
                btn_E.setIcon(btn_aux.getIcon());
                btn_D.setVisible(false);
                btn_E.setVisible(true);
            }
            else{
                if(btn_G.isVisible()==false){
                    btn_aux.setText(btn_D.getText());
                    btn_aux.setIcon(btn_D.getIcon());
                    
                    btn_D.setText(btn_G.getText());
                    btn_D.setIcon(btn_G.getIcon());
                    
                    btn_G.setText(btn_aux.getText());
                    btn_G.setIcon(btn_aux.getIcon());
                    btn_D.setVisible(false);
                    btn_G.setVisible(true);
                }
                else{
                    if(btn_C.isVisible()==false){
                        btn_aux.setText(btn_D.getText());
                        btn_aux.setIcon(btn_D.getIcon());
                        
                        btn_D.setText(btn_C.getText());
                        btn_D.setIcon(btn_C.getIcon());
                        
                        btn_C.setText(btn_aux.getText());
                        btn_C.setIcon(btn_aux.getIcon());
                        btn_D.setVisible(false);
                        btn_C.setVisible(true);
                    }
                    else{
                        System.out.println("No se puede mover");
                    }
                }
            }
        }
         
    }//GEN-LAST:event_btn_DActionPerformed

    private void btn_FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FActionPerformed
        
         javax.swing.JButton btn_aux = new javax.swing.JButton();
         if(btn_C.isVisible()==false){
             btn_aux.setText(btn_F.getText());
             btn_aux.setIcon(btn_F.getIcon());
             
             btn_F.setText(btn_C.getText());
             btn_F.setIcon(btn_C.getIcon());
             
             btn_C.setText(btn_aux.getText());
             btn_C.setIcon(btn_aux.getIcon());
             btn_F.setVisible(false);
             btn_C.setVisible(true);
        }
         else{
            if(btn_G.isVisible()==false){
                btn_aux.setText(btn_F.getText());
                btn_aux.setIcon(btn_F.getIcon());
                
                btn_F.setText(btn_G.getText()); 
                btn_F.setIcon(btn_G.getIcon());
                
                btn_G.setText(btn_aux.getText());
                btn_G.setIcon(btn_aux.getIcon());
                btn_F.setVisible(false);
                btn_G.setVisible(true);
            }
            else{
                    System.out.println("No se puede mover");
                }
        }
    }//GEN-LAST:event_btn_FActionPerformed

    private void btn_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BActionPerformed
        javax.swing.JButton btn_aux = new javax.swing.JButton();
         if(btn_A.isVisible()==false){
             btn_aux.setText(btn_B.getText());
             btn_aux.setIcon(btn_B.getIcon());
             
             btn_B.setText(btn_A.getText());
             btn_B.setIcon(btn_A.getIcon());
             
             btn_A.setText(btn_aux.getText());
             btn_A.setIcon(btn_aux.getIcon());
             btn_B.setVisible(false);
             btn_A.setVisible(true);
        }
         else{
            if(btn_E.isVisible()==false){
                btn_aux.setText(btn_B.getText());
                btn_aux.setIcon(btn_B.getIcon());
                
                btn_B.setText(btn_E.getText());
                btn_B.setIcon(btn_E.getIcon());
                
                btn_E.setText(btn_aux.getText());
                btn_E.setIcon(btn_aux.getIcon());
                btn_B.setVisible(false);
                btn_E.setVisible(true);
            }
            else{
                    System.out.println("No se puede mover");
                }
        } 
    }//GEN-LAST:event_btn_BActionPerformed

    private void btn_GActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GActionPerformed
        javax.swing.JButton btn_aux = new javax.swing.JButton();
        
        if(btn_F.isVisible()==false){
            btn_aux.setText(btn_G.getText());
            btn_aux.setIcon(btn_G.getIcon());
            
            btn_G.setText(btn_F.getText());
            btn_G.setIcon(btn_F.getIcon());
            
            btn_F.setText(btn_aux.getText());
            btn_F.setIcon(btn_aux.getIcon());
            btn_G.setVisible(false);
            btn_F.setVisible(true);
        }
        else{
            if(btn_D.isVisible()==false){
                btn_aux.setText(btn_G.getText());
                btn_aux.setIcon(btn_G.getIcon());
                
                btn_G.setText(btn_D.getText());
                btn_G.setIcon(btn_D.getIcon());
                
                btn_D.setText(btn_aux.getText());
                btn_D.setIcon(btn_aux.getIcon());
                btn_G.setVisible(false);
                btn_D.setVisible(true);
            }
            else{
                if(btn_H.isVisible()==false){
                    btn_aux.setIcon(btn_G.getIcon());
                     btn_aux.setText(btn_G.getText());
                     
                    btn_G.setIcon(btn_H.getIcon());
                    btn_G.setText(btn_H.getText());
                    
                    btn_H.setIcon(btn_aux.getIcon());
                    btn_H.setText(btn_aux.getText());
                    btn_G.setVisible(false);
                    btn_H.setVisible(true);
                }
                else{
                    System.out.println("No se puede mover");
                }
            }
        }

    }//GEN-LAST:event_btn_GActionPerformed

    private void btn_HActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HActionPerformed
        javax.swing.JButton btn_aux = new javax.swing.JButton();
         if(btn_E.isVisible()==false){
             btn_aux.setText(btn_H.getText());
             btn_aux.setIcon(btn_H.getIcon());
             btn_H.setText(btn_E.getText());
             btn_H.setIcon(btn_E.getIcon());
             btn_E.setText(btn_aux.getText());
             btn_E.setIcon(btn_aux.getIcon());
             btn_H.setVisible(false);
             btn_E.setVisible(true);
        }
         else{
            if(btn_G.isVisible()==false){
                btn_aux.setText(btn_H.getText());
                btn_aux.setIcon(btn_H.getIcon());
                btn_H.setText(btn_G.getText());
                btn_H.setIcon(btn_G.getIcon());
                btn_G.setText(btn_aux.getText());
                btn_G.setIcon(btn_aux.getIcon());
                btn_H.setVisible(false);
                btn_G.setVisible(true);
            }
            else{
                    System.out.println("No se puede mover");
                }
        } 
    }//GEN-LAST:event_btn_HActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        matriz_juego[0][0]= btn_Black.getText();
        matriz_juego[0][1]= btn_A.getText();
        matriz_juego[0][2]= btn_B.getText();
        matriz_juego[1][0]= btn_C.getText();
        matriz_juego[1][1]= btn_D.getText();
        matriz_juego[1][2]= btn_E.getText();
        matriz_juego[2][0]= btn_F.getText();
        matriz_juego[2][1]= btn_G.getText();
        matriz_juego[2][2]= btn_H.getText();
        imprimir_tablero();
        Jerarquia(1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EActionPerformed

        javax.swing.JButton btn_aux = new javax.swing.JButton();

        if(btn_B.isVisible()==false){
            btn_aux.setText(btn_E.getText());
            btn_aux.setIcon(btn_E.getIcon());
            btn_E.setText(btn_B.getText());
            btn_E.setIcon(btn_B.getIcon());
            btn_B.setText(btn_aux.getText());
            btn_B.setIcon(btn_aux.getIcon());
            btn_E.setVisible(false);
            btn_B.setVisible(true);
        }
        else{
            if(btn_D.isVisible()==false){
                btn_aux.setText(btn_E.getText());
                btn_aux.setIcon(btn_E.getIcon());
                btn_E.setText(btn_D.getText());
                btn_E.setIcon(btn_D.getIcon());
                btn_D.setText(btn_aux.getText());
                btn_D.setIcon(btn_aux.getIcon());
                btn_E.setVisible(false);
                btn_D.setVisible(true);
            }
            else{
                if(btn_H.isVisible()==false){
                    btn_aux.setText(btn_E.getText());
                    btn_aux.setIcon(btn_E.getIcon());
                    btn_E.setText(btn_H.getText());
                    btn_E.setIcon(btn_H.getIcon());
                    btn_H.setText(btn_aux.getText());
                    btn_H.setIcon(btn_aux.getIcon());
                    btn_E.setVisible(false);
                    btn_H.setVisible(true);
                }
                else{
                    System.out.println("No se puede mover");
                }
            }
        }
    }//GEN-LAST:event_btn_EActionPerformed

    private void Next_StepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Next_StepActionPerformed
        matriz_juego[0][0]= btn_Black.getText();
        matriz_juego[0][1]= btn_A.getText();
        matriz_juego[0][2]= btn_B.getText();
        matriz_juego[1][0]= btn_C.getText();
        matriz_juego[1][1]= btn_D.getText();
        matriz_juego[1][2]= btn_E.getText();
        matriz_juego[2][0]= btn_F.getText();
        matriz_juego[2][1]= btn_G.getText();
        matriz_juego[2][2]= btn_H.getText();
        imprimir_tablero();
        Jerarquia(2);
    }//GEN-LAST:event_Next_StepActionPerformed

    
    
    public void imprimir_tablero(){
    for(int i=0;i<3;i++){
        for(int j=0;j<3;j++){
            System.out.print(matriz_juego[i][j]);
        }
        System.out.print("\n");
    }
}
    

public void Jerarquia(int index){
    boolean flag=false;
    if(index==2){
       
        flag =true;
    }
    /*
    El segundo agente se encarga de verificar si se esta en optimo
    */
    Agente2 verificador= new Agente2(matriz_juego);
    Agente3 solucionador= new Agente3(matriz_juego);
    while(!verificador.Verificar_Optimo()){
        solucionador.Construir_ruta_optima(); 
        Actualizar_interfaz(); 
       // this.jPanel1.revalidate();//
        
       if(flag){//||global==true){
        //   global==false;
           
           break;
       }
       else{
           temporalizador();
           update(this.getGraphics());
       }
    }
    matriz_juego= ambiente.Estado_Actual;
    System.out.println("<<<<<<<<<<<<>>>>>>>>>>>>>>");
    imprimir_tablero();
    
}
public void temporalizador(){

        long temp =System.currentTimeMillis()+ 1000;
    while(System.currentTimeMillis()<temp){  
        
    }
   
}


public void Actualizar_interfaz(){
        Encender_todo();
        System.out.println("B1");
            
        Encontrar_Blanca();
        System.out.println("B2");
        btn_Black.setText(matriz_juego[0][0]);
        btn_Black.setIcon(new javax.swing.ImageIcon(getClass().getResource(Selector_Imagenes(matriz_juego[0][0]))));
        btn_A.setText(matriz_juego[0][1]);
        btn_A.setIcon(new javax.swing.ImageIcon(getClass().getResource(Selector_Imagenes(matriz_juego[0][1]))));
        btn_B.setText(matriz_juego[0][2]);
        btn_B.setIcon(new javax.swing.ImageIcon(getClass().getResource(Selector_Imagenes(matriz_juego[0][2]))));
        btn_C.setText(matriz_juego[1][0]);
        btn_C.setIcon(new javax.swing.ImageIcon(getClass().getResource(Selector_Imagenes(matriz_juego[1][0]))));
        btn_D.setText(matriz_juego[1][1]);
        btn_D.setIcon(new javax.swing.ImageIcon(getClass().getResource(Selector_Imagenes(matriz_juego[1][1]))));
        btn_E.setText(matriz_juego[1][2]);
        btn_E.setIcon(new javax.swing.ImageIcon(getClass().getResource(Selector_Imagenes(matriz_juego[1][2]))));
        btn_F.setText(matriz_juego[2][0]);
        btn_F.setIcon(new javax.swing.ImageIcon(getClass().getResource(Selector_Imagenes(matriz_juego[2][0]))));
        btn_G.setText(matriz_juego[2][1]);
        btn_G.setIcon(new javax.swing.ImageIcon(getClass().getResource(Selector_Imagenes(matriz_juego[2][1]))));
        btn_H.setText(matriz_juego[2][2]);
        btn_H.setIcon(new javax.swing.ImageIcon(getClass().getResource(Selector_Imagenes(matriz_juego[2][2]))));
}
public String Selector_Imagenes(String index){
    switch(index){
        case "*":return "/images/imgA.jpg";
        case "A":return "/images/imgA.jpg";
        case "B":return "/images/imgB.jpg";
        case "C":return "/images/imgC.jpg";
        case "D":return "/images/imgD.jpg";
        case "E":return "/images/imgE.jpg";
        case "F":return "/images/imgF.jpg";
        case "G":return "/images/imgG.jpg";
        case "H":return "/images/imgH.jpg";
        default: return "/images/imgI.jpg";                              
}
}

public void Encender_todo(){
    btn_Black.setVisible(true);
    btn_A.setVisible(true);
    btn_B.setVisible(true);
    btn_C.setVisible(true);
    btn_D.setVisible(true);
    btn_E.setVisible(true);
    btn_F.setVisible(true);
    btn_G.setVisible(true);
    btn_H.setVisible(true);
    
}

public void Encontrar_Blanca(){
    int i, j, x,y;
    boolean senial = false;
    x=0;
    y=0;
    i = 0;
    j = 0;
    while(i<3){
        while(j<3){
            if(matriz_juego[i][j].compareTo("*")==0){
                x=i;
                y=j;   
                senial= true;
                break;
            }
            else{
                j++;
            }
        }
        if(senial){
            break;
        }
        else {
            i++;
            j=0;
        }
    }
    Apagar_blanco(x,y);
}
public void Apagar_blanco(int indiceX, int indiceY){
    switch(indiceX){
        case 0:
            switch(indiceY){
                case 0:btn_Black.setVisible(false);break;
                case 1:btn_A.setVisible(false);break;
                case 2:btn_B.setVisible(false);break;
            }
            ;break;
        case 1:
            switch(indiceY){
                case 0:btn_C.setVisible(false);break;
                case 1:btn_D.setVisible(false);break;
                case 2:btn_E.setVisible(false);break;
            }
            ;break;
        case 2:
            switch(indiceY){
                case 0:btn_F.setVisible(false);break;
                case 1:btn_G.setVisible(false);break;
                case 2:btn_H.setVisible(false);break;
            }
            ;break;
    }
}

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Grupo;
    private javax.swing.JButton Next_Step;
    private javax.swing.JButton btn_A;
    private javax.swing.JButton btn_B;
    private javax.swing.JButton btn_Black;
    private javax.swing.JButton btn_C;
    private javax.swing.JButton btn_D;
    private javax.swing.JButton btn_E;
    private javax.swing.JButton btn_F;
    private javax.swing.JButton btn_G;
    private javax.swing.JButton btn_H;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private java.awt.TextArea textArea1;
    // End of variables declaration//GEN-END:variables
}
